<?php
/**
 * $Id: kannel_config_groups.inc.php 4 2008-12-28 07:41:19Z donald $:
 * Kannel Web Configuration 
 * Keeping it simple.
 *
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. 
 *  
 * This software is donationware. Meaning that if you find it useful or want to 
 * contribute to the development of this software, you can make a donation.
 *
 * Donations can be in the form of contributions to the code (patches), money
 * or hardware. Donator's will be recognized on the sponsors page or within the
 * source code.
 * 
 * http://www.ddj.co.za/kannel-web-configuration-tool/
 */

/**
 * This file is auto-generated by scripts/parser_cfg_def.php which accepts cfg.def files
 * from Kannel source
 */

$kannelConfigGroups = array();
$kannelConfigGroups['core'] = array();
	$kannelConfigGroups['core']['type'] = 'single';
	$kannelConfigGroups['core']['vars'] = array();
	$kannelConfigGroups['core']['vars']['admin-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['admin-port-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['admin-interface'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['admin-password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['status-password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['admin-deny-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['admin-allow-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['smsbox-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['smsbox-port-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['smsbox-max-pending'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['wapbox-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['wapbox-port-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['box-deny-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['box-allow-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['udp-deny-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['udp-allow-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['wdp-interface-name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['log-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['log-level'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['access-log'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['access-log-time'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['access-log-format'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['access-log-clean'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['store-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['store-dump-freq'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['store-type'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['store-location'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['unified-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['white-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['white-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['black-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['black-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['http-proxy-host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['http-proxy-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['http-proxy-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['http-proxy-exceptions'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['http-proxy-exceptions-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['http-proxy-username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['http-proxy-password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['ssl-client-certkey-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['ssl-server-cert-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['ssl-server-key-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['ssl-trusted-ca-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['dlr-storage'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['maximum-queue-length'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['sms-incoming-queue-limit'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['sms-outgoing-queue-limit'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['sms-resend-freq'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['sms-resend-retry'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['sms-combine-concatenated-mo'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['core']['vars']['sms-combine-concatenated-mo-timeout'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['wap-url-map'] = array();
	$kannelConfigGroups['wap-url-map']['type'] = 'multi';
	$kannelConfigGroups['wap-url-map']['vars'] = array();
	$kannelConfigGroups['wap-url-map']['vars']['name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-url-map']['vars']['url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-url-map']['vars']['map-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-url-map']['vars']['send-msisdn-query'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-url-map']['vars']['send-msisdn-header'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-url-map']['vars']['send-msisdn-format'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-url-map']['vars']['accept-cookies'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['wap-user-map'] = array();
	$kannelConfigGroups['wap-user-map']['type'] = 'multi';
	$kannelConfigGroups['wap-user-map']['vars'] = array();
	$kannelConfigGroups['wap-user-map']['vars']['name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-user-map']['vars']['user'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-user-map']['vars']['pass'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-user-map']['vars']['msisdn'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['wap-push-user'] = array();
	$kannelConfigGroups['wap-push-user']['type'] = 'multi';
	$kannelConfigGroups['wap-push-user']['vars'] = array();
	$kannelConfigGroups['wap-push-user']['vars']['wap-push-user'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['ppg-username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['ppg-password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['country-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['allowed-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['allowed-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['denied-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['denied-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['white-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['white-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['black-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['black-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['deny-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['allow-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['forced-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['default-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['dlr-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wap-push-user']['vars']['smsbox-id'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['smsbox-route'] = array();
	$kannelConfigGroups['smsbox-route']['type'] = 'multi';
	$kannelConfigGroups['smsbox-route']['vars'] = array();
	$kannelConfigGroups['smsbox-route']['vars']['smsbox-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox-route']['vars']['smsc-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox-route']['vars']['shortcode'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['smsc'] = array();
	$kannelConfigGroups['smsc']['type'] = 'multi';
	$kannelConfigGroups['smsc']['id'] = 'smsc-id';
	$kannelConfigGroups['smsc']['vars'] = array();
	$kannelConfigGroups['smsc']['vars']['smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['smsc-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['denied-smsc-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['allowed-smsc-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['preferred-smsc-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['allowed-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['denied-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['preferred-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['unified-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['reroute'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['reroute-smsc-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['reroute-receiver'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['reroute-dlr'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['log-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['log-level'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['our-host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['alt-dcs'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['throughput'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['alt-charset'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['alt-host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['use-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['alt-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['smsc-username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['smsc-password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['keepalive'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['sim-buffering'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['modemtype'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['device'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['speed'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['validityperiod'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['our-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['receive-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['connect-allow-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['system-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['system-type'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['address-range'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['smsc_nua'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['home_nua'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['wait_report'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['ois-debug-level'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['modem-type'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['pin'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['phone'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['send-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['dlr-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['sender-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['flow-control'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['wait-ack'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['wait-ack-expire'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['no-sender'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['no-coding'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['window'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['idle-timeout'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['no-sep'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['appname'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['ussdc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['session-length'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['my-number'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['sms-center'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['source-addr-ton'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['source-addr-npi'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['dest-addr-ton'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['dest-addr-npi'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['bind-addr-ton'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['bind-addr-npi'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['service-type'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['source-addr-autodetect'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['enquire-link-interval'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['max-pending-submits'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['reconnect-delay'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['transceiver-mode'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['interface-version'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['priority'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['notification-pid'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['notification-addr'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['msg-id-type'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['no-dlr'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['connection-timeout'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['allowed-smsc-id-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['denied-smsc-id-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['preferred-smsc-id-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['allowed-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['denied-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['preferred-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['max-error-count'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['alt-addr-charset'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['status-success-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['status-permfail-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['status-tempfail-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['max-sms-octets'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['login-prompt'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsc']['vars']['password-prompt'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['sms-service'] = array();
	$kannelConfigGroups['sms-service']['type'] = 'multi';
	$kannelConfigGroups['sms-service']['vars'] = array();
	$kannelConfigGroups['sms-service']['vars']['name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['keyword'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['aliases'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['get-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['post-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['post-xml'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['text'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['exec'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['accepted-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['accepted-smsc-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['accepted-account'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['accepted-account-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['forced-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['default-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['faked-sender'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['max-messages'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['concatenation'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['split-chars'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['split-suffix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['omit-empty'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['header'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['footer'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['suffix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['assume-plain-text'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['accept-x-kannel-headers'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['strip-keyword'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['send-sender'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['catch-all'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['allowed-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['allowed-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['denied-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['denied-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['allowed-receiver-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['allowed-receiver-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['denied-receiver-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['denied-receiver-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['white-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['white-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['black-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['black-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['dlr-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sms-service']['vars']['keyword-regex'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['sendsms-user'] = array();
	$kannelConfigGroups['sendsms-user']['type'] = 'multi';
	$kannelConfigGroups['sendsms-user']['vars'] = array();
	$kannelConfigGroups['sendsms-user']['vars']['name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['user-deny-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['user-allow-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['forced-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['default-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['faked-sender'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['default-sender'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['max-messages'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['concatenation'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['split-chars'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['split-suffix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['omit-empty'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['header'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['footer'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['allowed-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['denied-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['white-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['black-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['dlr-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['allowed-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['denied-prefix-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['white-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sendsms-user']['vars']['black-list-regex'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['ota-setting'] = array();
	$kannelConfigGroups['ota-setting']['type'] = 'multi';
	$kannelConfigGroups['ota-setting']['vars'] = array();
	$kannelConfigGroups['ota-setting']['vars']['ota-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['location'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['service'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['ipaddress'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['phonenumber'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['bearer'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['connection'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['calltype'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['speed'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['pppsecurity'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['authentication'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['login'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-setting']['vars']['secret'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['ota-bookmark'] = array();
	$kannelConfigGroups['ota-bookmark']['type'] = 'multi';
	$kannelConfigGroups['ota-bookmark']['vars'] = array();
	$kannelConfigGroups['ota-bookmark']['vars']['ota-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-bookmark']['vars']['name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ota-bookmark']['vars']['url'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['modems'] = array();
	$kannelConfigGroups['modems']['type'] = 'multi';
	$kannelConfigGroups['modems']['vars'] = array();
	$kannelConfigGroups['modems']['vars']['id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['detect-string'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['detect-string2'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['init-string'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['speed'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['enable-hwhs'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['need-sleep'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['no-pin'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['no-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['sendline-sleep'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['keepalive-cmd'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['broken'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['message-storage'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['enable-mms'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['modems']['vars']['reset-string'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['mysql-connection'] = array();
	$kannelConfigGroups['mysql-connection']['type'] = 'multi';
	$kannelConfigGroups['mysql-connection']['vars'] = array();
	$kannelConfigGroups['mysql-connection']['vars']['id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['mysql-connection']['vars']['host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['mysql-connection']['vars']['port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['mysql-connection']['vars']['username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['mysql-connection']['vars']['password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['mysql-connection']['vars']['database'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['mysql-connection']['vars']['max-connections'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['oracle-connection'] = array();
	$kannelConfigGroups['oracle-connection']['type'] = 'multi';
	$kannelConfigGroups['oracle-connection']['vars'] = array();
	$kannelConfigGroups['oracle-connection']['vars']['id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['oracle-connection']['vars']['username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['oracle-connection']['vars']['password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['oracle-connection']['vars']['tnsname'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['oracle-connection']['vars']['max-connections'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['sdb-connection'] = array();
	$kannelConfigGroups['sdb-connection']['type'] = 'multi';
	$kannelConfigGroups['sdb-connection']['vars'] = array();
	$kannelConfigGroups['sdb-connection']['vars']['id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sdb-connection']['vars']['url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sdb-connection']['vars']['max-connections'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['pgsql-connection'] = array();
	$kannelConfigGroups['pgsql-connection']['type'] = 'multi';
	$kannelConfigGroups['pgsql-connection']['vars'] = array();
	$kannelConfigGroups['pgsql-connection']['vars']['id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['pgsql-connection']['vars']['host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['pgsql-connection']['vars']['port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['pgsql-connection']['vars']['username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['pgsql-connection']['vars']['password'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['pgsql-connection']['vars']['database'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['pgsql-connection']['vars']['max-connections'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['sqlite3-connection'] = array();
	$kannelConfigGroups['sqlite3-connection']['type'] = 'multi';
	$kannelConfigGroups['sqlite3-connection']['vars'] = array();
	$kannelConfigGroups['sqlite3-connection']['vars']['id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sqlite3-connection']['vars']['database'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['sqlite3-connection']['vars']['max-connections'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['wapbox'] = array();
	$kannelConfigGroups['wapbox']['type'] = 'single';
	$kannelConfigGroups['wapbox']['vars'] = array();
	$kannelConfigGroups['wapbox']['vars']['bearerbox-host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['timer-freq'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['url-map'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-max'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-0'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-1'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-2'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-3'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-4'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-5'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-6'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-7'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-8'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['map-url-9'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['device-home'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['log-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['log-level'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['syslog-level'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['smart-errors'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['access-log'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['access-log-time'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['access-log-clean'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['http-interface-name'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['concatenation'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['max-messages'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wapbox']['vars']['wml-strict'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['wtls'] = array();
	$kannelConfigGroups['wtls']['type'] = 'single';
	$kannelConfigGroups['wtls']['vars'] = array();
	$kannelConfigGroups['wtls']['vars']['certificate-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wtls']['vars']['privatekey-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['wtls']['vars']['privatekey-password'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['ppg'] = array();
	$kannelConfigGroups['ppg']['type'] = 'single';
	$kannelConfigGroups['ppg']['vars'] = array();
	$kannelConfigGroups['ppg']['vars']['ppg-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['ppg-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['ppg-ssl-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['trusted-pi'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['concurrent-pushes'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['users'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['ppg-allow-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['ppg-deny-ip'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['ssl-server-cert-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['ssl-server-key-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['global-sender'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['default-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['default-dlr-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['ppg-smsbox-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['ppg']['vars']['service-name'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['test-ppg'] = array();
	$kannelConfigGroups['test-ppg']['type'] = 'single';
	$kannelConfigGroups['test-ppg']['vars'] = array();
	$kannelConfigGroups['test-ppg']['vars']['retries'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['test-ppg']['vars']['pi-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['test-ppg']['vars']['ssl-client-certkey-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['test-ppg']['vars']['ssl-trusted-ca-file'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['configuration'] = array();
	$kannelConfigGroups['configuration']['type'] = 'single';
	$kannelConfigGroups['configuration']['vars'] = array();
	$kannelConfigGroups['configuration']['vars']['push-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['configuration']['vars']['content-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['configuration']['vars']['pap-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['configuration']['vars']['username'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['configuration']['vars']['password'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['smsbox'] = array();
	$kannelConfigGroups['smsbox']['type'] = 'single';
	$kannelConfigGroups['smsbox']['vars'] = array();
	$kannelConfigGroups['smsbox']['vars']['smsbox-id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['bearerbox-host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['bearerbox-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['bearerbox-port-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['sendsms-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['sendsms-port-ssl'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['sendsms-interface'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['sendsms-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['sendota-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['xmlrpc-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['sendsms-chars'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['global-sender'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['log-file'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['log-level'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['access-log'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['access-log-time'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['access-log-clean'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['sms-length'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['reply-couldnotfetch'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['reply-couldnotrepresent'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['reply-requestfailed'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['reply-emptymessage'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['allowed-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['denied-prefix'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['white-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['black-list'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['mo-recode'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['http-request-retry'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['http-queue-delay'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['white-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['black-list-regex'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['immediate-sendsms-reply'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['smsbox']['vars']['max-pending-requests'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['dlr-db'] = array();
	$kannelConfigGroups['dlr-db']['type'] = 'single';
	$kannelConfigGroups['dlr-db']['vars'] = array();
	$kannelConfigGroups['dlr-db']['vars']['id'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['table'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-smsc'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-timestamp'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-source'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-destination'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-service'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-url'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-mask'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-status'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['dlr-db']['vars']['field-boxc-id'] = array('type' => 'string', 'default' => '');



$kannelConfigGroups['radius-acct'] = array();
	$kannelConfigGroups['radius-acct']['type'] = 'single';
	$kannelConfigGroups['radius-acct']['vars'] = array();
	$kannelConfigGroups['radius-acct']['vars']['our-host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['our-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['remote-host'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['remote-port'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['remote-timeout'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['nas-ports'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['secret-nas'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['secret-radius'] = array('type' => 'string', 'default' => '');
	$kannelConfigGroups['radius-acct']['vars']['unified-prefix'] = array('type' => 'string', 'default' => '');



?>